import{a as q,S as B,i as c}from"./assets/vendor-C9vNCoLC.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const E="https://pixabay.com/api/",P="50679981-3c82f9b846616ba31889c4405";async function p(o,t,a){try{return(await q.get(E,{params:{key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:a}})).data}catch(n){throw n}}const h=document.querySelector(".gallery"),y=document.querySelector(".loader"),g=document.querySelector(".load-btn"),$=new B(".gallery a");function b(o){const t=o.map(({webformatURL:a,largeImageURL:n,tags:e,likes:r,views:i,comments:v,downloads:S})=>`<li class="photo-card">
          <a href="${n}">
            <img src="${a}" alt="${e}" loading="lazy" />
          </a>
          <div class="info">
            <p class="info-item"><b>Likes</b><br>${r}</p>
            <p class="info-item"><b>Views</b><br>${i}</p>
            <p class="info-item"><b>Comments</b><br>${v}</p>
            <p class="info-item"><b>Downloads</b><br>${S}</p>
          </div>
        </li>
      `).join("");h.insertAdjacentHTML("beforeend",t),$.refresh()}function O(){h.innerHTML=""}function L(){y.classList.add("active")}function u(){y.classList.remove("active")}function w(){g.classList.add("active")}function f(){g.classList.remove("active")}const x=document.querySelector(".form"),H=document.querySelector('input[name="search-text"]'),I=document.querySelector(".load-btn");let l="",s=1;const d=15;let m=0;x.addEventListener("submit",async o=>{if(o.preventDefault(),l=H.value.trim(),!l){c.error({message:"Enter a search query!"});return}s=1,O(),f(),L();try{const t=await p(l,s,d);if(m=t.totalHits,u(),t.hits.length===0){c.error({id:"error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",transitionIn:"fadeInDown"});return}b(t.hits),s*d<m&&w()}catch{u(),c.error({title:"Error",message:"Something went wrong. Please try again later."})}});function M(){const o=document.querySelector(".photo-card");if(o){const t=o.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}}I.addEventListener("click",async()=>{s+=1,L(),f();try{const o=await p(l,s,d);u(),b(o.hits),M(),s*d>=m?(c.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomRight"}),f()):w()}catch{u(),c.error({title:"Error",message:"Something went wrong."})}});
//# sourceMappingURL=index.js.map
