import{a as v,S as E,i as c}from"./assets/vendor-C9vNCoLC.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const B="https://pixabay.com/api/",P="50679981-3c82f9b846616ba31889c4405";async function f(o,t,s){try{return(await v.get(B,{params:{key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:s}})).data}catch(n){throw n}}const h=document.querySelector(".gallery"),g=document.querySelector(".load-btn"),y=document.querySelector(".loader-container"),_=new E(".gallery a",{captionsData:"alt",captionDelay:250});function L(o){const t=o.map(({webformatURL:s,largeImageURL:n,tags:e,likes:r,views:i,comments:S,downloads:q})=>`
      <li class="gallery-item">
        <a class="gallery__link" href="${n}">
          <img class="gallery__image" src="${s}" alt="${e}" />
        </a>
        <div class="image-info">
          <p>Likes: <span>${r}</span></p>
          <p>Views: <span>${i}</span></p>
          <p>Comments: <span>${S}</span></p>
          <p>Downloads: <span>${q}</span></p>
        </div>
      </li>
    `).join("");h.insertAdjacentHTML("beforeend",t),_.refresh()}function $(){h.innerHTML=""}function w(){y.classList.remove("is-hidden")}function d(){y.classList.add("is-hidden")}function b(){g.classList.remove("is-hidden")}function p(){g.classList.add("is-hidden")}const O=document.querySelector(".form"),x=document.querySelector('input[name="search-text"]'),D=document.querySelector(".load-btn");let l="",a=1;const u=15;let m=0;O.addEventListener("submit",async o=>{if(o.preventDefault(),l=x.value.trim(),!l){c.error({message:"Enter a search query!"});return}a=1,$(),p(),w();try{const t=await f(l,a,u);if(m=t.totalHits,d(),t.hits.length===0){c.error({id:"error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",transitionIn:"fadeInDown"});return}L(t.hits),a*u<m&&b()}catch{d(),c.error({title:"Error",message:"Something went wrong. Please try again later."})}});function H(){const o=document.querySelector(".gallery-item");if(o){const t=o.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}}D.addEventListener("click",async()=>{a+=1,w(),p();try{const o=await f(l,a,u);d(),L(o.hits),H(),a*u>=m?(c.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomRight"}),p()):b()}catch{d(),c.error({title:"Error",message:"Something went wrong."})}});
//# sourceMappingURL=index.js.map
